GEM-50 | Add group remove
Group-Expense-Manager/group-manager pull request #13
Opened 2024-08-07 20:11 UTC by lawos98

2024-08-09 15:20 UTC, pwgacek requested changes

2024-08-09 15:20 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/external/controller/ApiExceptionHandler.kt
please add handling finance adapter client exceptions

2024-08-10 19:38 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/external/controller/ApiExceptionHandler.kt
added

2024-08-11 08:21 UTC, pwgacek approved these changes

2024-08-14 15:49 UTC, merged