GEM-75 | Add external GET user groups
Group-Expense-Manager/group-manager pull request #6
Opened 2024-05-22 16:52 UTC by lawos98

2024-05-25 10:08 UTC, pwgacek requested changes
What about GroupServiceTest?

2024-05-25 10:08 UTC, pwgacek commented on src/test/kotlin/pl/edu/agh/gem/external/dto/ExternalUserGroupsResponseTest.kt
> +        externalUserGroupsResponse.groups.shouldBe(listOf())
```suggestion
        externalUserGroupsResponse.groups shouldBe listOf()
```

2024-05-26 13:23 UTC, pwgacek approved these changes

2024-05-26 13:23 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/service/GroupService.kt
> +class UserWithoutGroup(userId: String) :
```suggestion
class UserWithoutGroupException(userId: String) :
```

2024-05-28 18:42 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/internal/service/GroupService.kt
> +class UserWithoutGroup(userId: String) :
fixed

2024-05-28 18:46 UTC, merged